# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad5baa16a5eb2bc3b3e44cc399f709a34383c5399c6730e1e4abc0877f2106f8ba7b775b8d4e4a9907e10349837b169aa81feeb6155fc3a42a8f5b408ffb9372

test:
  secret_key_base: e2dd260715e0f5dcf3a8640dd1a9211b337711eb4e685bc72ef012a12947a2b66229a936405e8dbd0ea96d4d0d90b5a1160905e3f2bf46b476f4c3d340fd200c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
